<?php

namespace Sea\Components;

/**
 * Test class for ComponentInjector.
 * Generated by PHPUnit on 2011-07-17 at 00:04:59.
 */
class ComponentInjectorTest extends \PHPUnit_Framework_TestCase {

    /**
     * @var ComponentInjector
     */
    protected $cinjector;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->cinjector = new ComponentInjector;
    }

    public function testGetClassName()
    {
        $cookieClassName = $this->cinjector->getClassName('cookie');
        $this->assertEquals('Core\\Components\\Cookie', $cookieClassName);
    }

}

?>
