<?php

namespace Core\Components;

/**
 * Test class for Request.
 * Generated by PHPUnit on 2011-07-14 at 21:25:26.
 */
class RequestTest extends \PHPUnit_Framework_TestCase {

    /**
     * @var Request
     */
    protected $request;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->request = new Request('subdomain.example.com', '/users/');
    }

    /**
     * @todo Implement testGetSubdomain().
     */
    public function testGetSubdomain() {
        $this->assertEquals('subdomain', $this->request->getSubdomain());
    }

    /**
     * @todo Implement testGetHostname().
     */
    public function testGetHostname() {
        $this->assertEquals('example', $this->request->getHostname());
    }

    /**
     * @todo Implement testGetRoute().
     */
    public function testGetRoute() {
        $this->assertEquals('/users/', $this->request->getRoute());
    }

    /**
     * @todo Implement testGetMethod().
     */
    public function testGetMethod() {
       $this->assertEquals('GET', $this->request->getMethod());
    }

    /**
     * @todo Implement testIsSSL().
     */
    public function testIsSSL() {
        $this->assertEquals(false, $this->request->isSSL());
    }

    /**
     * @todo Implement testIsAjax().
     */
    public function testIsAjax() {
        $this->assertEquals(false, $this->request->isAjax());
    }

    /**
     * @todo Implement testRedirect().
     */
    public function testRedirect() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

}

?>
